server:
  port: 8085


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qppp?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: S@pph4grace


  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update

      # Allows Hibernate to generate SQL optimized for a particular DBMS
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: victoronushaibu@gmail.com
    password: shaibuonuv1

    #other properties
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

#          use this links to allow access to your email... https://myaccount.google.com/security ... https://accounts.google.com/b/0/DisplayUnlockCaptcha




